import React from 'react';

export const formHelp = 
<div style={{fontFamily: 'Lato', fontSize: 20, background: '#f5f5f0'}}>
  <p style={{display: 'inline-block'}}><strong>Sightseeing: </strong> 
    Enter the various sightseeings in the city along with the duration and start timings. 
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>From City: </strong> 
    Choose the service city where the sightseeing takes place
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Active Services: </strong> 
    By default, only active services are listed. To list the inactive 
    ones as well, toggle the 'Active Services' switch
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Active Services: </strong> 
    By default, only active services are listed. To list the inactive 
    ones as well, toggle the 'Active Services' switch. The inactive ones
    will be listed in red.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Private: </strong> 
    If private is ticked, the sightseeing is not picked up while building 
    auto-itinerary. Only non-private entries are considered while 
    auto-selecting the sightseeing in a city.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Recommended: </strong> 
    If recommended is ticked, the sightseeing is chosen while building 
    the auto-itinerary. This flag is also used when the service costing 
    report is created, which allows you to filter on only the 
    recommended sightseeing.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Refundable: </strong> 
    Whether the amount is refundable is the tour is cancelled. This is 
    further carried to the module costing and then to the invoicing.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Day At Leisure: </strong> 
    If ticked, the sightseeing is not included in the costing and no 
    voucher is created for this.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Advance Booking Required: </strong> 
    If ticked, this sightseeing is included in the list of hotel 
    confirmation request emails
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Guide Required: </strong> 
    If ticked, a guide is auto-seleted for this itinerary while building
    the auto-itinerary
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Transport Required: </strong> 
    If ticked, it indicates that transport is required for the sightseeing
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Day Excursion: </strong> 
    Tick for services such as Delhi-Agra-Delhi where the entire to & fro
    journey as well as the sightseeing is completed in a day. If ticked, 
    and the nights in the city you do the sightsseing in is 0, then 
    auto-transfers are not generated by the system as the transfer cost
    is included within the costing of the sightseeing.
  </p><br></br>
</div>

export const mainFormHelp = 
<div style={{fontFamily: 'Lato', fontSize: 20, background: '#f5f5f0'}}>
  <p style={{display: 'inline-block'}}><strong>Sightseeing: </strong> 
    Enter the various sightseeings in the city along with the duration and start timings. 
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>From City: </strong> 
    Choose the service city where the sightseeing takes place
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Active Services: </strong> 
    By default, only active services are listed. To list the inactive 
    ones as well, toggle the 'Active Services' switch
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Active Services: </strong> 
    By default, only active services are listed. To list the inactive 
    ones as well, toggle the 'Active Services' switch. The inactive ones
    will be listed in red.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Private: </strong> 
    If private is ticked, the sightseeing is not picked up while building 
    auto-itinerary. Only non-private entries are considered while 
    auto-selecting the sightseeing in a city.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Recommended: </strong> 
    If recommended is ticked, the sightseeing is chosen while building 
    the auto-itinerary. This flag is also used when the service costing 
    report is created, which allows you to filter on only the 
    recommended sightseeing.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Refundable: </strong> 
    Whether the amount is refundable is the tour is cancelled. This is 
    further carried to the module costing and then to the invoicing.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Day At Leisure: </strong> 
    If ticked, the sightseeing is not included in the costing and no 
    voucher is created for this.
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Advance Booking Required: </strong> 
    If ticked, this sightseeing is included in the list of hotel 
    confirmation request emails
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Guide Required: </strong> 
    If ticked, a guide is auto-seleted for this itinerary while building
    the auto-itinerary
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Transport Required: </strong> 
    If ticked, it indicates that transport is required for the sightseeing
  </p><br></br>
  <p style={{display: 'inline-block'}}><strong>Day Excursion: </strong> 
    Tick for services such as Delhi-Agra-Delhi where the entire to & fro
    journey as well as the sightseeing is completed in a day. If ticked, 
    and the nights in the city you do the sightsseing in is 0, then 
    auto-transfers are not generated by the system as the transfer cost
    is included within the costing of the sightseeing.
  </p><br></br>
</div>
